# language: php
filter:
  excluded_paths:
    - docs/
checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
build:
  nodes:
    node620:
      environment:
        node: v6.2.0
      dependencies:
        override:
          - npm install
      tests:
        override:
          - node_modules/.bin/standard --fix init.js
          - node_modules/.bin/standard init.js
    php708:
      environment:
        php: 7.0.8
      dependencies:
        override:
          - composer install
      tests:
        override:
          - vendor/bin/phpcbf -p --standard=PSR2 controller.php
          - vendor/bin/phpcs -p --standard=PSR2 controller.php
          - php-scrutinizer-run
